server:
  port: 8761

  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: eureka-monitor-server

eureka:
  server:
    enableSelfPreservation: false 
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2    
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
