server:
  contextPath: /stock
  port: 9000

spring:
  application:
    name: stock

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      preferIpAddress: true