server:
  contextPath: /gateway
  port: 8080

spring:
  application:
    name: service-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true